apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::557600925814:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-MH9UWIOX9AS7
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::557600925814:role/UdacityFlaskDeployCBKubectlRole
      username: build   
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-09T20:08:25Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "4449"
  uid: e3b43f5b-c752-4992-8713-58e109b987de
